-- 04-events.sql

-- Create the events table
CREATE TABLE IF NOT EXISTS public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    subtitle TEXT NOT NULL,
    event_date TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    created_by BIGINT REFERENCES public.base_users(id),
    body TEXT NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

-- Policies for events table
CREATE POLICY "events_select_for_all" ON public.events
    FOR SELECT
    USING (true);

CREATE POLICY "events_manage_by_permission" ON public.events
    FOR ALL
    USING (public.current_user_has_permission('MANAGE_EVENTS'::text))
    WITH CHECK (public.current_user_has_permission('MANAGE_EVENTS'::text));

-- Grant permissions
GRANT ALL ON TABLE public.events TO anon;
GRANT ALL ON TABLE public.events TO authenticated;
GRANT ALL ON TABLE public.events TO service_role;
