SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pgsodium";
CREATE EXTENSION IF NOT EXISTS "btree_gist" WITH SCHEMA "public";
CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

COMMENT ON SCHEMA "public" IS 'standard public schema';

SET default_tablespace = '';
SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."obljube" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "who" bigint NOT NULL,
    "minister" bigint NOT NULL,
    "amount" integer NOT NULL,
    "reason" "text" NOT NULL
);
ALTER TABLE "public"."obljube" OWNER TO "postgres";
COMMENT ON TABLE "public"."obljube" IS 'Obljube records with amount and reason.';
ALTER TABLE "public"."obljube" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."obljube_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."obljube"
    ADD CONSTRAINT "obljube_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."obljube"
    ADD CONSTRAINT "obljube_who_fkey" FOREIGN KEY ("who") REFERENCES "public"."base_users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."obljube"
    ADD CONSTRAINT "obljube_minister_fkey" FOREIGN KEY ("minister") REFERENCES "public"."base_users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."obljube" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "obljube_select_authenticated" ON "public"."obljube" FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "obljube_insert_add_obljuba" ON "public"."obljube" FOR INSERT TO "authenticated" WITH CHECK (public.current_user_has_permission('ADD_OBLJUBA'::text));
CREATE POLICY "obljube_delete_add_obljuba" ON "public"."obljube" FOR DELETE TO "authenticated" USING (public.current_user_has_permission('ADD_OBLJUBA'::text));

GRANT ALL ON TABLE "public"."obljube" TO "anon";
GRANT ALL ON TABLE "public"."obljube" TO "authenticated";
GRANT ALL ON TABLE "public"."obljube" TO "service_role";
GRANT ALL ON SEQUENCE "public"."obljube_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."obljube_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."obljube_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";

RESET ALL;
