
  create table "public"."events" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "event_date" timestamp with time zone,
    "created_at" timestamp with time zone not null default now(),
    "created_by" bigint,
    "body" text
      );


alter table "public"."events" enable row level security;

CREATE UNIQUE INDEX events_pkey ON public.events USING btree (id);

CREATE UNIQUE INDEX permission_types_name_key ON public.permission_types USING btree (name);

alter table "public"."events" add constraint "events_pkey" PRIMARY KEY using index "events_pkey";

alter table "public"."events" add constraint "events_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.base_users(id) not valid;

alter table "public"."events" validate constraint "events_created_by_fkey";

alter table "public"."permission_types" add constraint "permission_types_name_key" UNIQUE using index "permission_types_name_key";

grant delete on table "public"."events" to "anon";

grant insert on table "public"."events" to "anon";

grant references on table "public"."events" to "anon";

grant select on table "public"."events" to "anon";

grant trigger on table "public"."events" to "anon";

grant truncate on table "public"."events" to "anon";

grant update on table "public"."events" to "anon";

grant delete on table "public"."events" to "authenticated";

grant insert on table "public"."events" to "authenticated";

grant references on table "public"."events" to "authenticated";

grant select on table "public"."events" to "authenticated";

grant trigger on table "public"."events" to "authenticated";

grant truncate on table "public"."events" to "authenticated";

grant update on table "public"."events" to "authenticated";

grant delete on table "public"."events" to "service_role";

grant insert on table "public"."events" to "service_role";

grant references on table "public"."events" to "service_role";

grant select on table "public"."events" to "service_role";

grant trigger on table "public"."events" to "service_role";

grant truncate on table "public"."events" to "service_role";

grant update on table "public"."events" to "service_role";


  create policy "events_manage_by_permission"
  on "public"."events"
  as permissive
  for all
  to public
using (public.current_user_has_permission('MANAGE_EVENTS'::text))
with check (public.current_user_has_permission('MANAGE_EVENTS'::text));



  create policy "events_select_for_all"
  on "public"."events"
  as permissive
  for select
  to public
using (true);



