ALTER SEQUENCE "public"."washing_machines_id_seq"
	AS integer
	INCREMENT BY 1
	MINVALUE 1 MAXVALUE 2147483647
	START WITH 1 CACHE 1 NO CYCLE
;

CREATE TABLE "public"."obljube" (
	"id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 NO CYCLE),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"who" bigint NOT NULL,
	"minister" bigint NOT NULL,
	"amount" integer NOT NULL,
	"reason" text COLLATE "pg_catalog"."default" NOT NULL
);

CREATE POLICY "obljube_delete_add_obljuba" ON "public"."obljube"
	AS PERMISSIVE
	FOR DELETE
	TO authenticated
	USING (current_user_has_permission('ADD_OBLJUBA'::text));

CREATE POLICY "obljube_insert_add_obljuba" ON "public"."obljube"
	AS PERMISSIVE
	FOR INSERT
	TO authenticated
	WITH CHECK (current_user_has_permission('ADD_OBLJUBA'::text));

CREATE POLICY "obljube_select_authenticated" ON "public"."obljube"
	AS PERMISSIVE
	FOR SELECT
	TO authenticated
	USING (true);

CREATE POLICY "obljube_update_add_obljuba" ON "public"."obljube"
	AS PERMISSIVE
	FOR UPDATE
	TO authenticated
	WITH CHECK (current_user_has_permission('ADD_OBLJUBA'::text));

ALTER TABLE "public"."obljube" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."obljube" ADD CONSTRAINT "obljube_minister_fkey" FOREIGN KEY (minister) REFERENCES base_users(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;

ALTER TABLE "public"."obljube" VALIDATE CONSTRAINT "obljube_minister_fkey";

ALTER TABLE "public"."obljube" ADD CONSTRAINT "obljube_who_fkey" FOREIGN KEY (who) REFERENCES base_users(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;

ALTER TABLE "public"."obljube" VALIDATE CONSTRAINT "obljube_who_fkey";

CREATE UNIQUE INDEX  obljube_pkey ON public.obljube USING btree (id);

ALTER TABLE "public"."obljube" ADD CONSTRAINT "obljube_pkey" PRIMARY KEY USING INDEX "obljube_pkey";

