-- Paying off obljube. obljube stays an untouched record of what was promised;
-- every beer sold to someone who owes beer is logged in obljube_poplacila
-- against their oldest open obljuba (only obljube that existed at the time of
-- the sale). Owed = amount - sum(poplacila), computed in the views below.
-- Deleting a sale cascades to its poplacila, so the obljuba is owed again.

CREATE TABLE IF NOT EXISTS public.obljube_poplacila (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    obljuba_id bigint NOT NULL REFERENCES public.obljube(id) ON UPDATE CASCADE ON DELETE CASCADE,
    -- null for manual entries (odpis, plačilo izven sistema)
    transaction_id bigint REFERENCES public.transactions(id) ON UPDATE CASCADE ON DELETE CASCADE,
    amount integer NOT NULL CHECK (amount > 0),
    created_by bigint REFERENCES public.base_users(id) ON UPDATE CASCADE ON DELETE SET NULL,
    note text
);
ALTER TABLE public.obljube_poplacila OWNER TO postgres;
COMMENT ON TABLE public.obljube_poplacila IS 'Log of beers paid off against obljube, from sales or added manually.';

CREATE INDEX IF NOT EXISTS obljube_poplacila_obljuba_id_idx ON public.obljube_poplacila (obljuba_id);
CREATE INDEX IF NOT EXISTS obljube_poplacila_transaction_id_idx ON public.obljube_poplacila (transaction_id);

ALTER TABLE public.obljube_poplacila ENABLE ROW LEVEL SECURITY;

-- sales write through the trigger below; people only add or remove manual entries
CREATE POLICY obljube_poplacila_select_authenticated ON public.obljube_poplacila
    FOR SELECT TO authenticated USING (true);
CREATE POLICY obljube_poplacila_insert_manual ON public.obljube_poplacila
    FOR INSERT TO authenticated
    WITH CHECK (transaction_id IS NULL AND public.current_user_has_permission('ADD_OBLJUBA'::text));
CREATE POLICY obljube_poplacila_delete_manual ON public.obljube_poplacila
    FOR DELETE TO authenticated
    USING (transaction_id IS NULL AND public.current_user_has_permission('ADD_OBLJUBA'::text));

GRANT ALL ON TABLE public.obljube_poplacila TO authenticated;
GRANT ALL ON TABLE public.obljube_poplacila TO service_role;

CREATE OR REPLACE FUNCTION public.settle_obljube_from_transaction()
RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path = ''
    AS $$
DECLARE
    beers bigint;
    ob record;
    pay integer;
BEGIN
    -- an edited sale is settled again from scratch
    IF TG_OP = 'UPDATE' THEN
        DELETE FROM public.obljube_poplacila WHERE transaction_id = NEW.id;
    END IF;

    SELECT NEW.ordered * i.beer_count INTO beers
    FROM public.items i
    WHERE i.id = NEW.item;

    IF coalesce(beers, 0) <= 0 THEN
        RETURN NEW;
    END IF;

    -- serialize concurrent sales to the same person
    PERFORM 1 FROM public.obljube o WHERE o.who = NEW.customer_id FOR UPDATE;

    FOR ob IN
        SELECT o.id,
               o.amount - coalesce(
                   (SELECT sum(p.amount) FROM public.obljube_poplacila p WHERE p.obljuba_id = o.id),
                   0) AS remaining
        FROM public.obljube o
        WHERE o.who = NEW.customer_id
          AND o.created_at <= NEW.ordered_at
        ORDER BY o.created_at, o.id
    LOOP
        EXIT WHEN beers <= 0;
        CONTINUE WHEN ob.remaining <= 0;
        pay := least(beers, ob.remaining);
        INSERT INTO public.obljube_poplacila (obljuba_id, transaction_id, amount)
        VALUES (ob.id, NEW.id, pay);
        beers := beers - pay;
    END LOOP;

    RETURN NEW;
END;
$$;
ALTER FUNCTION public.settle_obljube_from_transaction() OWNER TO postgres;
REVOKE ALL ON FUNCTION public.settle_obljube_from_transaction() FROM PUBLIC, anon, authenticated;

CREATE TRIGGER transactions_settle_obljube
    AFTER INSERT OR UPDATE OF customer_id, ordered, item, ordered_at ON public.transactions
    FOR EACH ROW EXECUTE FUNCTION public.settle_obljube_from_transaction();

-- paid / remaining appended (CREATE OR REPLACE VIEW can only add columns at the end)
CREATE OR REPLACE VIEW public.obljube_with_user_info AS
SELECT
    o.*,
    bu_who.id AS user_id,
    bu_who.created_at AS user_created_at,
    bu_who.name AS user_name,
    bu_who.surname AS user_surname,
    bu_who.auth AS user_auth_id,
    bu_who.resident AS user_resident_id,
    bu_who.invited_by AS user_invited_by,
    bu_minister.id AS minister_id,
    bu_minister.name AS minister_name,
    coalesce(paid.amount, 0)::integer AS paid,
    greatest(o.amount - coalesce(paid.amount, 0), 0)::integer AS remaining
FROM
    public.obljube o
    LEFT JOIN public.base_users bu_who ON o.who = bu_who.id
    LEFT JOIN public.base_users bu_minister ON o.minister = bu_minister.id
    LEFT JOIN (
        SELECT obljuba_id, sum(amount) AS amount
        FROM public.obljube_poplacila
        GROUP BY obljuba_id
    ) paid ON paid.obljuba_id = o.id;

CREATE OR REPLACE VIEW public.top_obljube_users_sum AS
WITH user_totals AS (
  SELECT
    o.who,
    o.user_name,
    o.user_surname,
    sum(o.amount) AS total_amount,
    sum(o.paid) AS total_paid,
    sum(o.remaining) AS total_remaining
  FROM public.obljube_with_user_info o
  GROUP BY o.who, o.user_name, o.user_surname
)
SELECT who, user_name, user_surname, total_amount, total_paid, total_remaining
FROM user_totals;
